name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: apps/web

      - name: Build project
        run: npm run build
        working-directory: apps/web
